network:
  projection_head:
    mlp_hidden_size: 512
    projection_size: 128

trainer:
  batch_size: 64
  m: 0.996 # momentum update
  max_epochs: 300
  num_workers: 4
  ft: 62
  class_start: 0
  class_end: 9
  lr: 0.001
  weight_decay: 0.0001

iteration: 100

finetune:
  batch_size: 10
  test_batch_size: 10
  epochs: 100
  ft: 62
  class_start: 10
  class_end: 15
  lr: 0.001
  weight_decay: 0.0001
  k_shot: 5